version: "3"

services:

  database:
      image: kartoza/postgis:9.6-2.4
      env_file:
        - database.env
      deploy:
        resources:
          limits:
            cpus: "2"
            memory: 2048M
        restart_policy:
          condition: on-failure
      ports:
        - "5432:5432"
      volumes:
        - ~/AppData/ReadinessPlatform/pgdata:/var/lib/postgresql
      networks:
        - databasenet

networks:
  databasenet:
