version: "3"

services:

  api:
    image: foresight/api:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8180"
    volumes:
      - ./api/public_html:/src/public_html
    entrypoint:
      - yarn
      - run
      - start
    networks:
      - apinet

  geoserver:
    image: foresight/geoserver:2.12.1
    deploy:
      resources:
        limits:
          cpus: "10"
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver/gsdata:/opt/geoserver/data_dir
      - ./geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    networks:
      - geoservernet

networks:
  apinet:
  geoservernet:
